### ISSUE TITLE
pagination?

### ISSUE THREAD

**Issue by akhoury** [ASCIIcat/nodebb-plugin-import-mybb#1]
i hate to ask you to do the work again, but it seems that you've written this plugin based on 
https://github.com/psychobunny/nodebb-plugin-import-phpbb

Which needs to be updated to support pagination see this pull request
https://github.com/psychobunny/nodebb-plugin-import-phpbb/pull/5

if you want want, look at this _branch_ (patch-1) that I forked and diff it with your repo here and make the changes to add pagination support.
https://github.com/akhoury/nodebb-plugin-import-phpbb/tree/patch-1

Pagination is critical for large databases, so the process won't run out of memory.

**Comment by ASCIIcat** [comment]
Fair point I'll include that now. 
Just got the import working with a small site as test. 
But pagination is indeed needed for larger databases

**Comment by akhoury** [comment]
another reason is the usage of `IN` in this mysql query
https://github.com/ASCIIcat/nodebb-plugin-import-mybb/blob/master/index.js#L272

that's extremely slow and needs to be replaced by either a fancy join, or a pre-cache call which is what I did here
https://github.com/akhoury/nodebb-plugin-import-phpbb/blob/patch-1/index.js#L214

however, now that I looked at it again, it seems that I need to fix something in that `getTopicsMainPids` function to use pagination it self - but thats no big deal now, you can still merge the diff and i will clone the fix to your repo as well.

**Comment by ASCIIcat** [comment]
fixed in https://github.com/ASCIIcat/nodebb-plugin-import-mybb/commit/e309f5598349c514a50007ed505b09080959deb9

added pagination support as per the above pull request
